name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 2025.2.0
      - latest
      - main
  pull_request:

jobs:
  build-stable:
    name: Build ${{ matrix.firmware.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
          - file:  tests/ehtmxv2-template.yaml
            name: EHMTX template
            manifest_filename: ehtmxv2-template-manifest.json
      fail-fast: false
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: 2025.2.0
      - name: Build firmware
        uses: esphome/build-action@v6
        id: esphome-build
        with:
          yaml_file: ${{ matrix.firmware.file }}
          version: latest
