name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 2025.2.0
      - latest
      - main
  pull_request:

jobs:
  build-stable:
    name: Compile test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: 2025.2.0
      - name: Build firmware
        uses: esphome/build-action@v6
        id: esphome-build
        with:
          yaml-file: ./tests/ehtmxv2-template.yaml
          version: dev

